// const MongoClient = require('mongodb').MongoClient;

//Object destructring
const {MongoClient, ObjectID} = require('mongodb');

MongoClient.connect('mongodb://localhost:27017/TodoApp', (err, db) => {
  if (err) {
    return console.log('Unable to connect to MongoDB server');
  }
  console.log('Connected to MongoDB server');

  // db.collection('Todos').insertOne({
  //   text: 'Something to do',
  //   completed: false
  // }, (err, result) => {
  //   if (err) {
  //     return console.log('Unable to insert todo', err);
  //   }
  //
  //   console.log(JSON.stringify(result.ops, undefined, 2));
  // });

  // Insert new doc into Users (name, age, location)
  // db.collection('Users').insertOne({
  //   name: 'Andrew',
  //   age: 25,
  //   location: 'Philadelphia'
  // }, (err, result) => {
  //   if (err) {
  //     return console.log('Unable to insert user', err);
  //   }
  //Gets timestamp from id property
  //   console.log(result.ops[0]._id.getTimestamp());
  // });

  db.close();
});

/*
1.ObjectID
id:5a0701831c4b421c77c3c3b4  This is the default ide generated by mongodb
Its 12 byte value
1st four bytes are a timestamp
next 3 are machine identifiers i.e. if 2 machine generate id their id's will be different
next 2 are process id just make unique identifier
next is 3 byte counter this is what sql would do


2.We can create our own id by specifing it
for e.g _id: 123

3.ES6 object destructing
eg var user = {name:'andrew',age:25}
var {name} = user;
console.log(name); => andrew
 */